preset: recommended

risky: true

linting: true

enabled:
  - align_equals
  - combine_consecutive_unsets
  - concat_with_spaces
  - const_visibility_required
  - declare_strict_types
  - dir_constant
  - echo_to_print
  - ereg_to_preg
  - mb_str_functions
  - modernize_types_casting
  - no_blank_lines_after_return
  - no_trailing_whitespace_in_comment
  - no_blank_lines_before_namespace
  - no_empty_comment
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - ordered_class_elements
  - php_unit_construct
  - php_unit_dedicate_assert
  - phpdoc_add_missing_param_annotation
  - pow_to_exponentiation
  - protected_to_private
  - random_api_migration
  - return_type_declaration

disabled:
  - blank_line_after_opening_tag
  - class_keyword_remove
  - phpdoc_no_empty_return
  - self_accessor

finder:
  exclude:
    - "build"
    - "vendor"
    - "tests"
  name:
    - "*.php"
