# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Markdown Lint"

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  text-lint:
    name: "Markdown lint"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      - name: set git credentials
        run: |
          git config --local user.email "d.bannert@anolilab.de"
          git config --local user.name "Daniel Bannert"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install

      - run: npm run lint
